SELECT * FROM PRACTICE

--DISTINCT OPERATOR
SELECT distinct Department FROM PRACTICE

--COUNT OPERATOR
SELECT COUNT(department) from practice

--DISTINCT OPERATOR
select DISTINCT FIRSTNAME FROM PRACTICE

--COUNT OPERATOR
SELECT COUNT (distinct department) from practice

--COUNT(*) OPERATOR
select count(*) department from practice

--NOT EQUAL != OPERATOR
SELECT * FROM EMPLOYEE WHERE Department <> 'Finance';

--EQUAL TO = OPERATOR
SELECT * FROM EMPLOYEE WHERE first_name = 'John';

--GREATER THAN > OPERATOR
SELECT * FROM EMPLOYEE WHERE AGE > 30;

--LESS THAN < OPERATOR
SELECT * FROM EMPLOYEE WHERE SALARY < 50000;

--GREATER THAN EQUAL TO >= OPERATOR
SELECT * FROM EMPLOYEE WHERE SALARY >= 50000;

--GREATER THAN EQUAL TO <=
SELECT * FROM EMPLOYEE WHERE AGE >= 40;

--BETWEEN OPERATOR
SELECT * FROM EMPLOYEE WHERE AGE BETWEEN 30 AND 40;

--LIKE % OPERATOR
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE 'E%'


--IN OPERATOR
SELECT * FROM EMPLOYEE WHERE DEPARTMENT IN ('Marketing','Finance','HR');

--IS NULL OPERATOR
